name: QqGroupAccess
version: '${project.version}'
main: cn.paper_card.qq_group_access.QqGroupAccess
api-version: '1.20'
author: Paper99
folia-supported: true

depend:
  - PaperCardMirai
  - PlayerQqBind
  - PlayerQqGroupRemark
  - PlayerQqInGroup
  - GroupRootCommand

commands:
  qq-group-access:
    permission: qq-group-access.command

permissions:
  qq-group-access.command:
    default: true


